# meta-luckfox/conf/layer.conf
#
# Machine / integration layer for the Luckfox Pico Ultra.
# Depends on meta-luckfox-bsp for low-level board support.

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "luckfox"
BBFILE_PATTERN_luckfox = "^${LAYERDIR}/"
BBFILE_PRIORITY_luckfox = "11"

LAYERDEPENDS_luckfox = "core yocto openembedded-layer luckfox-bsp"
LAYERSERIES_COMPAT_luckfox = "scarthgap"
