# meta-luckfox-bsp/conf/layer.conf
#
# BSP layer for the Luckfox Pico Ultra board family.
# Provides kernel, bootloader and low-level board support for Rockchip RV1106.

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "luckfox-bsp"
BBFILE_PATTERN_luckfox-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_luckfox-bsp = "10"

LAYERDEPENDS_luckfox-bsp = "core yocto openembedded-layer"
LAYERSERIES_COMPAT_luckfox-bsp = "scarthgap"
